#!/usr/bin/env node
/**
 * Dispatch CLI for agistra.dev
 * Reads project increment queues and routes work to the right agent and model.
 * Generated by setchin-agent-profiles deploy — do not edit directly.
 */
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { dispatch } from './dispatch.js';
import { scan } from './scan.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const consultingRoot = path.resolve(__dirname, '..');

// sibling project repos live at: workspaceRoot/<project-name>/
const workspaceRoot = path.resolve(consultingRoot, '..');

function parseArgs(argv) {
	const result = {};
	for (let i = 0; i < argv.length; i++) {
		const arg = argv[i];
		if (arg.startsWith('--')) {
			const key = arg.slice(2);
			const next = argv[i + 1];
			result[key] = (next && !next.startsWith('--')) ? next : true;
			if (next && !next.startsWith('--')) i++;
		} else if (!result._command) {
			result._command = arg;
		} else if (!result._project) {
			result._project = arg;
		}
	}
	return result;
}

const args   = parseArgs(process.argv.slice(2));
const command = args._command ?? 'dispatch';

// --project flag takes precedence over positional project name
const project = typeof args.project === 'string' ? args.project : args._project;

const projectsRoot = path.resolve(consultingRoot, args['projects-root'] ?? 'projects');
const skillsRoot   = path.resolve(consultingRoot, args['skills-root']   ?? '.github/skills');
const projectsDir  = project ? path.join(projectsRoot, project) : null;
const projectRoot  = project ? path.join(workspaceRoot, project) : null;

if (command === 'dispatch') {
	const advance = args.advance === true;
	const list    = args.list    === true;
	const launch  = args.launch  === true;
	const task    = typeof args.task === 'string' ? args.task : null;
	dispatch({ projectsRoot, skillsRoot, project, advance, list, launch, projectRoot, task });

} else if (command === 'scan') {
	const dryRun = args['dry-run'] === true;
	scan({ projectRoot, projectName: project, projectsDir, dryRun });

} else {
	process.stdout.write([
		'Usage:',
		'  node cli/index.js dispatch [<project>]                           # show current increment prompt',
		'  node cli/index.js dispatch <project> --list                     # show all project queues',
		'  node cli/index.js dispatch <project> --advance                  # mark done, show next',
		'  node cli/index.js dispatch <project> --launch                   # launch Claude in the project dir',
		'  node cli/index.js dispatch <project> --task <num-or-slug>         # dispatch a specific task',
		'  node cli/index.js scan     <project>             # scan project and generate increments',
		'  node cli/index.js scan     <project> --dry-run   # preview without writing files',
		'',
		'Or via npm scripts:',
		'  npm run list',
		'  npm run dispatch <project>',
		'  npm run advance  <project>',
		'  npm run launch   <project>',
		'  npm run scan     <project>',
		'',
	].join('\n'));
	process.exit(0);
}
