#!/usr/bin/env node
/**
 * Workspace setup wizard.
 *
 * Collects user / org / agent configuration and writes a gitignored
 * workspace.config.json to the target output directory. Then generates
 * platform-specific personalisation overlays for each detected platform.
 *
 * Run from the source repo:   npm run setup "D:/path/to/hub"
 * Run from a deployed hub:    npm run setup
 */
import readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { wireTelegramMcp } from './wizard.js';

// ── Pure helpers (exported for testing) ───────────────────────────────────────

/**
 * Detect which platform agent directories are present in the given root.
 *
 * @param {string} root  Absolute path to the workspace root.
 * @returns {{ claude: boolean, cursor: boolean, github: boolean }}
 */
export function detectPlatforms(root) {
	return {
		claude: fs.existsSync(path.join(root, '.claude', 'agents')),
		cursor: fs.existsSync(path.join(root, '.cursor', 'agents')),
		github: fs.existsSync(path.join(root, '.github', 'agents')),
	};
}

/**
 * Build the shared personalisation body text from a workspace config object.
 * Used by both the Cursor and GitHub generators.
 *
 * @param {object} config  Parsed workspace.config.json object.
 * @returns {string}
 */
export function buildPersonalisationContent(config) {
	const lines = [];

	// User identity
	lines.push('## Workspace Identity');
	lines.push('');
	lines.push(`- **Name:** ${config.user?.name ?? ''}`);
	lines.push(`- **Role:** ${config.user?.role ?? ''}`);
	lines.push(`- **Organisation:** ${config.org ?? ''}`);

	// Agent display names
	const agents = config.agents ?? {};
	const agentEntries = Object.entries(agents);
	if (agentEntries.length > 0) {
		lines.push('');
		lines.push('## Agent Display Names');
		lines.push('');
		for (const [id, { displayName }] of agentEntries) {
			lines.push(`- **${id}:** ${displayName}`);
		}
	}

	// Remote team
	const rt = config.remoteTeam;
	if (rt?.enabled) {
		lines.push('');
		lines.push('## Remote Team');
		lines.push('');
		lines.push(`- **Remote team name:** ${rt.name ?? ''}`);
		lines.push(`- **Remote agent name:** ${rt.agentName ?? ''}`);

		const handle = rt.telegram?.handle;
		if (handle) {
			lines.push(`- **Telegram handle:** ${handle}`);
		}

		if (rt.telegram) {
			lines.push('- **Telegram bot token:** see workspace.config.json → remoteTeam.telegram.botToken');
		}
	}

	return lines.join('\n');
}

const GENERATED_HEADER = '<!-- Generated by setup.js — do not edit manually -->';

/**
 * Generate .cursor/rules/workspace-identity.mdc for the given workspace root.
 *
 * @param {string} root    Absolute path to the workspace root.
 * @param {object} config  Parsed workspace.config.json object.
 */
export function generateCursorIdentity(root, config) {
	const rulesDir = path.join(root, '.cursor', 'rules');
	fs.mkdirSync(rulesDir, { recursive: true });

	const frontmatter = [
		'---',
		'description: Workspace identity and personalisation for Cursor agents',
		'alwaysApply: true',
		'---',
	].join('\n');

	const body = buildPersonalisationContent(config);
	const content = `${GENERATED_HEADER}\n${frontmatter}\n\n${body}\n`;

	fs.writeFileSync(path.join(rulesDir, 'workspace-identity.mdc'), content, 'utf-8');
}

/**
 * Generate .github/copilot-instructions.md for the given workspace root.
 *
 * @param {string} root    Absolute path to the workspace root.
 * @param {object} config  Parsed workspace.config.json object.
 */
export function generateGithubCopilotInstructions(root, config) {
	const githubDir = path.join(root, '.github');
	fs.mkdirSync(githubDir, { recursive: true });

	const body = buildPersonalisationContent(config);
	const content = `${GENERATED_HEADER}\n\n${body}\n`;

	fs.writeFileSync(path.join(githubDir, 'copilot-instructions.md'), content, 'utf-8');
}

// ── Token sentinel (exported for testing) ─────────────────────────────────────

/**
 * Sentinel value shown in the bot-token prompt when a token is already stored.
 * If the user presses Enter without typing, ask() returns this string.
 * setup.run() checks for equality: if the returned value matches, the existing
 * token is preserved silently. If the user types anything else, that replaces it.
 */
export const TOKEN_SENTINEL = '[token set — press Enter to keep]';

// ── Testable run factory (exported for unit tests) ─────────────────────────────

/**
 * Create a run() function with injectable I/O and filesystem.
 * Separating the run logic from the real readline/fs lets unit tests drive the
 * wizard without spawning a subprocess or touching real files.
 *
 * @param {object} deps
 * @param {function(string, string=): Promise<string>} deps.ask
 *   Prompt for a string value. Should honour a defaultValue parameter.
 * @param {function(string, boolean=): Promise<boolean>} deps.askYN
 *   Prompt for a yes/no value. Should honour a defaultYes parameter.
 * @param {function(string=): void} deps.line
 *   Print a visual section separator.
 * @param {object} deps.fsMod
 *   Injectable fs module (real fs or an in-memory mock).
 * @param {string} deps.cliOutputRoot
 *   Absolute path to the workspace root being configured.
 * @returns {function(): Promise<void>}
 */
export function createRun({ ask, askYN, line, fsMod, cliOutputRoot }) {
	return async function run() {
		// ── Read existing config (pre-populate defaults) ──────────────────────────
		let existingConfig = null;
		const configPath = path.join(cliOutputRoot, 'workspace.config.json');
		if (fsMod.existsSync(configPath)) {
			try {
				existingConfig = JSON.parse(fsMod.readFileSync(configPath, 'utf-8'));
			} catch {
				// Unparseable config — treat as fresh run
			}
		}

		const prev = existingConfig ?? {};
		const prevRemoteTeam = prev.remoteTeam ?? {};
		const prevTelegram = prev.telegram ?? {};
		const prevTgHandle = prevRemoteTeam.telegram?.handle ?? '';
		const prevTgGroupId = prevTelegram.relay_group_id ?? '';
		const prevBotToken = prevTelegram.bot_token ?? '';

		// ── Prompts ────────────────────────────────────────────────────────────────

		process.stdout.write('\n╔══════════════════════════════════════════════╗\n');
		process.stdout.write('║           Agent Workspace Setup              ║\n');
		process.stdout.write('╚══════════════════════════════════════════════╝\n');

		line('You ');
		const userName = await ask('Your name', prev.user?.name ?? '');
		const userRole = await ask('Your role (e.g. Technical Lead)', prev.user?.role ?? 'Technical Lead');

		line('Organisation ');
		const orgName = await ask('Organisation or team name', prev.org ?? '');

		line('Remote team ');
		const hasRemoteTeam = await askYN('Do you work with a remote team?', prevRemoteTeam.enabled === true);

		let remoteTeam = { enabled: false };
		let telegramMcp = null;
		if (hasRemoteTeam) {
			const remoteTeamName = await ask('Remote team name', prevRemoteTeam.name ?? 'Remote Team');
			const remoteAgentName = await ask('Remote agent name', prevRemoteTeam.agentName ?? 'Remote Agent');
			const hasTelegram = await askYN(
				'Does the remote team use Telegram?',
				prevRemoteTeam.telegram != null,
			);
			if (hasTelegram) {
				const telegramHandle = await ask('Telegram bot handle (e.g. @mybot)', prevTgHandle);
				const tokenDefault = prevBotToken ? TOKEN_SENTINEL : '';
				const tokenAnswer = await ask('Telegram bot token (from @BotFather)', tokenDefault);
				const telegramToken = tokenAnswer === TOKEN_SENTINEL ? prevBotToken : tokenAnswer;
				const telegramGroupId = await ask('Relay group ID (e.g. -1001234567890)', prevTgGroupId);
				remoteTeam = {
					enabled: true,
					name: remoteTeamName,
					agentName: remoteAgentName,
					telegram: { handle: telegramHandle },
				};
				telegramMcp = { enabled: true, bot_token: telegramToken, relay_group_id: telegramGroupId };
			} else {
				remoteTeam = { enabled: true, name: remoteTeamName, agentName: remoteAgentName };
			}
		}

		// Detect which platforms are present
		const platforms = detectPlatforms(cliOutputRoot);

		// Ask confirmation per detected platform (skip Claude — workspace.config.json is sufficient)
		let configureCursor = false;
		let configureGithub = false;

		if (platforms.cursor) {
			line('Cursor ');
			configureCursor = await askYN('Generate Cursor workspace identity rule?', true);
		}

		if (platforms.github) {
			line('GitHub ');
			configureGithub = await askYN('Generate GitHub Copilot instructions?', true);
		}

		const config = {
			user: { name: userName, role: userRole },
			org: orgName,
			remoteTeam,
			...(telegramMcp ? { telegram: telegramMcp } : {}),
		};

		// Preserve existing agents block (preserves display names across re-runs)
		if (existingConfig?.agents) {
			config.agents = existingConfig.agents;
		}

		fsMod.mkdirSync(cliOutputRoot, { recursive: true });
		fsMod.writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n', 'utf-8');

		// Warn if .gitignore does not cover the config file
		const gitignorePath = path.join(cliOutputRoot, '.gitignore');
		let gitignoreCovers = false;
		if (fsMod.existsSync(gitignorePath)) {
			const gi = fsMod.readFileSync(gitignorePath, 'utf-8');
			gitignoreCovers = gi.split('\n').some(l => l.trim() === 'workspace.config.json');
		}

		// Wire Telegram MCP into detected platform configs
		if (telegramMcp) {
			const targets = [
				...(platforms.claude ? ['claude-code'] : []),
				...(platforms.cursor ? ['cursor'] : []),
			];
			line('Telegram MCP ');
			const { wrote } = wireTelegramMcp({ config, workspaceRoot: cliOutputRoot, targets });
			if (wrote.length > 0) {
				for (const f of wrote) process.stdout.write(`  MCP wired → ${f}\n`);
			}
		}

		line('Done ');
		process.stdout.write(`  Config written → ${configPath}\n`);

		if (configureCursor) {
			generateCursorIdentity(cliOutputRoot, config);
			process.stdout.write(`  Cursor identity → ${path.join(cliOutputRoot, '.cursor', 'rules', 'workspace-identity.mdc')}\n`);
		}

		if (configureGithub) {
			generateGithubCopilotInstructions(cliOutputRoot, config);
			process.stdout.write(`  GitHub Copilot → ${path.join(cliOutputRoot, '.github', 'copilot-instructions.md')}\n`);
		}

		if (!gitignoreCovers) {
			process.stdout.write('\n  WARNING: workspace.config.json is not listed in .gitignore.\n');
			process.stdout.write('  Add the following line to prevent committing personal config:\n\n');
			process.stdout.write('    workspace.config.json\n');
		}

		if (!remoteTeam.enabled) {
			process.stdout.write('\n  Remote team disabled — Router will run in minimal mode.\n');
			process.stdout.write('  Re-run setup and enable remote team to unlock relay skills.\n');
		}

		process.stdout.write('\n');
	};
}

// ── CLI entry point (only runs when executed directly, not when imported) ──────

function parseCliArgs(argv) {
	const result = {};
	for (let i = 0; i < argv.length; i++) {
		const arg = argv[i];
		if (arg.startsWith('--')) {
			const key = arg.slice(2);
			const next = argv[i + 1];
			result[key] = (next && !next.startsWith('--')) ? next : true;
			if (next && !next.startsWith('--')) i++;
		}
	}
	return result;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
	const cliArgs = parseCliArgs(process.argv.slice(2));
	const cliOutputRoot = cliArgs.output ? path.resolve(cliArgs.output) : path.resolve('.');

	const rl = readline.createInterface({ input, output });

	function ask(question, defaultValue = '') {
		const hint = defaultValue ? ` [${defaultValue}]` : '';
		return rl.question(`${question}${hint}: `).then(a => a.trim() || defaultValue);
	}

	function askYN(question, defaultYes = false) {
		const hint = defaultYes ? ' [Y/n]' : ' [y/N]';
		return rl.question(`${question}${hint}: `).then(a => {
			const v = a.trim().toLowerCase();
			if (!v) return defaultYes;
			return v === 'y' || v === 'yes';
		});
	}

	function line(label = '') {
		const dashes = '─'.repeat(Math.max(0, 44 - label.length));
		process.stdout.write(`\n── ${label}${dashes}\n\n`);
	}

	const run = createRun({ ask, askYN, line, fsMod: fs, cliOutputRoot });

	run().then(() => {
		rl.close();
	}).catch(err => {
		rl.close();
		process.stderr.write(err.message + '\n');
		process.exit(1);
	});
}
