#!/usr/bin/env node
/**
 * Dispatch CLI for setchin-consulting-ai.
 * Reads project increment queues and routes work to the right agent and model.
 * Generated by setchin-agent-profiles deploy.
 */
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { dispatch } from './dispatch.js';
import { scan } from './scan.js';
import { findSkillCatalogEntry, installSkillFromCatalog } from './lib/skill-sources.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// setchin-consulting-ai/ root is two levels up from pipelines/deploy/
const consultingRoot = path.resolve(__dirname, '..', '..');
// workspace root is the parent of setchin-consulting-ai/
// sibling project repos live at: workspaceRoot/<project-name>/
const workspaceRoot = path.resolve(consultingRoot, '..');

const BOOLEAN_FLAGS = new Set(['advance', 'list', 'launch', 'dry-run']);

function parseArgs(argv) {
	const result = {};
	for (let i = 0; i < argv.length; i++) {
		const arg = argv[i];
		if (arg.startsWith('--')) {
			const key = arg.slice(2);
			const next = argv[i + 1];
			if (BOOLEAN_FLAGS.has(key)) {
				result[key] = true;
			} else {
				result[key] = (next && !next.startsWith('--')) ? next : true;
				if (next && !next.startsWith('--')) i++;
			}
		} else if (!result._command) {
			result._command = arg;
		} else if (!result._project) {
			// second positional = project name (enables: npm run scan vscode-ai-fleet)
			result._project = arg;
		} else if (!result._task) {
			// third positional = task number or slug (enables: npm run advance -- <project> 35)
			result._task = arg;
		}
	}
	return result;
}

const args   = parseArgs(process.argv.slice(2));
const command = args._command ?? 'dispatch';

// --project flag takes precedence over positional project name
const project = typeof args.project === 'string' ? args.project : args._project;

const projectsRoot = path.resolve(consultingRoot, args['projects-root'] ?? 'projects');
const skillsRoot   = path.resolve(consultingRoot, args['skills-root']   ?? 'skills');
const projectsDir  = project ? path.join(projectsRoot, project) : null;
const projectRoot  = project ? path.join(workspaceRoot, project) : null;

if (command === 'dispatch') {
	const advance = args.advance === true;
	const list    = args.list    === true;
	const launch  = args.launch  === true;
	const task    = typeof args.task === 'string' ? args.task : args._task ?? null;
	dispatch({ projectsRoot, skillsRoot, project, advance, list, launch, projectRoot, task });

} else if (command === 'scan') {
	const dryRun = args['dry-run'] === true;
	scan({ projectRoot, projectName: project, projectsDir, hubRoot: consultingRoot, dryRun });

// ── install-skill ─────────────────────────────────────────────────────────────
//
// Opt-in, user-initiated fetch of a third-party skill directly from its
// declared source into the CURRENT WORKING DIRECTORY's own skills/<name>/.
//
// This is meant to be run from inside this hub's own checkout. It never
// writes into, reads from as a destination, or otherwise touches
// setchin-agent-profiles' own skills/ directory or git history. It is never
// invoked by `deploy`, `deploy:dist`, or any CI step — see
// docs/product/optional-third-party-skills-PRD.md for the full rationale (licensing:
// third-party skill content is not ours to redistribute).

} else if (command === 'install-skill') {
	const name = typeof args.name === 'string' ? args.name : args._project;
	const catalogPath = path.join(consultingRoot, 'skill-catalog.json');
	const destRoot = path.join(process.cwd(), 'skills');

	if (!name) {
		process.stderr.write('Usage: node pipelines/deploy/index.js install-skill <name>\n');
		process.exit(1);
	}

	const entry = findSkillCatalogEntry(catalogPath, name);
	if (!entry) {
		console.error(`Unknown skill "${name}". Not found in skill-catalog.json.`);
		process.exit(1);
	}

	installSkillFromCatalog({ entry, destRoot }).then((result) => {
		if (result.status === 'error') {
			console.error(`ERROR [install-skill/${result.name}]: ${result.error}`);
			process.exit(1);
		}
		console.log(`[install-skill] ${result.name} → ${path.relative(process.cwd(), path.join(destRoot, result.name))} — ${result.status}`);
		process.exit(0);
	});

} else {
	process.stdout.write([
		'Usage:',
		'  node pipelines/deploy/index.js dispatch [<project>]                           # show current increment prompt',
		'  node pipelines/deploy/index.js dispatch <project> --list                     # show all project queues',
		'  node pipelines/deploy/index.js dispatch <project> --advance                  # mark lowest todo done, show next',
		'  node pipelines/deploy/index.js dispatch <project> --advance --task <N>     # mark task N done, show next',
		'  node pipelines/deploy/index.js dispatch <project> --advance <N>            # same (npm: advance -- <project> <N>)',
		'  node pipelines/deploy/index.js dispatch <project> --launch                   # launch Claude in the project dir',
		'  node pipelines/deploy/index.js dispatch <project> --task <num-or-slug>         # dispatch a specific task',
		'  node pipelines/deploy/index.js scan     <project>             # scan project and generate increments',
		'  node pipelines/deploy/index.js scan     <project> --dry-run   # preview without writing files',
		'  node pipelines/deploy/index.js install-skill <name>           # fetch a third-party skill into this hub\'s skills/',
		'',
		'Or via npm scripts:',
		'  npm run list',
		'  npm run dispatch <project>',
		'  npm run advance  <project> [taskN]',
		'  npm run launch   <project>',
		'  npm run scan     <project>',
		'  npm run install-skill <name>',
		'',
	].join('\n'));
	process.exit(0);
}
